var WTC = WTC || {};
// Only Package 3 tables and the minimal audit dependencies. No Private economics.
WTC.Schema = {
  T_STOCK_RECEIPTS: 'RECEIPT_ID|RECEIPT_REF|SOURCE_PARTY_ID|RECEIVED_DATE|RECEIVED_BY|EXPECTED_STATUS|CHECK_STATUS|REFERENCE_TEXT|EVIDENCE_GROUP_ID|STATUS|CREATED_AT|CREATED_BY|UPDATED_AT|UPDATED_BY'.split('|'),
  T_STOCK_RECEIPT_LINES: 'RECEIPT_LINE_ID|RECEIPT_ID|SKU_ID|EXPECTED_QTY|ACTUAL_QTY|CONDITION_CODE|ECONOMIC_OWNER_ID|AGREEMENT_REF_ID|VARIANCE_QTY|VARIANCE_STATUS|BATCH_ID|STATUS|CREATED_AT|CREATED_BY'.split('|'),
  T_BATCHES: 'BATCH_ID|SKU_ID|SOURCE_PARTY_ID|ECONOMIC_OWNER_ID|RECEIPT_LINE_ID|RECEIVED_AT|ORIGINAL_QTY|CONDITION_CODE|AGREEMENT_REF_ID|STATUS|CREATED_AT|CREATED_BY'.split('|'),
  T_INVENTORY_MOVEMENTS: 'MOVEMENT_ID|BATCH_ID|SKU_ID|FROM_LOCATION_ID|TO_LOCATION_ID|QTY|MOVEMENT_TYPE|BUSINESS_REASON_CODE|SOURCE_ENTITY_TYPE|SOURCE_ENTITY_ID|APPROVAL_ID|REVERSAL_OF_ID|NOTES|POSTED_AT|POSTED_BY|EVENT_ID'.split('|'),
  T_STOCK_COMMITMENTS: 'COMMITMENT_ID|SKU_ID|BATCH_ID|LOCATION_ID|COMMITMENT_TYPE|SOURCE_ENTITY_TYPE|SOURCE_ENTITY_ID|QTY|START_AT|EXPIRES_AT|STATUS|RELEASED_AT|RELEASE_REASON|CREATED_AT|CREATED_BY|EVENT_ID'.split('|'),
  SYS_RECONCILIATION: 'CHECK_ID|CHECK_TYPE|SCOPE|EXPECTED_VALUE|ACTUAL_VALUE|VARIANCE|RELATED_ENTITY_TYPE|RELATED_ENTITY_ID|SEVERITY|STATUS|CHECKED_AT|CHECKED_BY'.split('|'),
  T_EVENTS: 'EVENT_ID|EVENT_TYPE|EVENT_VERSION|SOURCE_SYSTEM|ENTITY_TYPE|ENTITY_ID|CORRELATION_ID|IDEMPOTENCY_KEY|ACTOR_TYPE|ACTOR_ID|OCCURRED_AT|RECORDED_AT|RESULT_STATUS|PAYLOAD_REF'.split('|'),
  T_EXCEPTIONS: 'EXCEPTION_ID|EXCEPTION_TYPE|RELATED_ENTITY_TYPE|RELATED_ENTITY_ID|SEVERITY|DETECTED_AT|DETECTED_BY|OWNER_PARTY_ID|RESOLUTION_CODE|RESOLUTION_AT|EVIDENCE_GROUP_ID|NOTES|STATUS|CREATED_AT|UPDATED_AT'.split('|')
};
